### PR TITLE
Revert numpy version for docker build

### PR DESCRIPTION
**Pull request by alhirzel**
I was having issues with the pinned `numpy` version (1.22.0) conflicting as follows, so this PR downgrades `numpy` to 1.21.6. The error is below.

```
#0 31.99 ERROR: Cannot install -r requirements.txt (line 19), -r requirements.txt (line 21), -r requirements.txt (line 24), -r requirements.txt (line 29) and numpy==1.22.0 because these package versions have conflicting dependencies.
#0 31.99 
#0 31.99 The conflict is caused by:
#0 31.99     The user requested numpy==1.22.0
#0 31.99     h5py 3.6.0 depends on numpy>=1.14.5
#0 31.99     jplephem 2.17 depends on numpy
#0 31.99     keras-preprocessing 1.1.2 depends on numpy>=1.9.1
#0 31.99     numba 0.55.1 depends on numpy<1.22 and >=1.18
#0 31.99 
#0 31.99 To fix this you could try to:
#0 31.99 1. loosen the range of package versions you've specified
#0 31.99 2. remove package versions to allow pip attempt to solve the dependency conflict
#0 31.99 
#0 31.99 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

It's very possible a better fix exists!

### CODE REVIEW

**Comment by HaroldMills** [comment]
Thanks for reporting this issue. I'm looking into requiring Numba 0.56 instead of 0.55, which should work with NumPy 1.22. I am reluctant to revert NumPy to 1.21, since it was bumped to 1.22 for security reasons. I'll aim to push some sort of fix early next week.

**Comment by alhirzel** [comment]
Great feedback, thank you. I just modified this PR so that it bumps `numba` and `llvmlite` rather than holding `numpy` back. This set of versions resolves locally for me. If you have any questions next week, just tag me, and I'll reply asap. Thank you for your work on this software!

**Comment by HaroldMills** [comment]
Thanks for the pull request. After merging it, I've gone ahead and updated several package version numbers to the most recent ones. I tested the newer packages with Vesper over the weekend, processing the recordings I made during that period without issue.

**Comment by alhirzel** [comment]
I did a quick test as well, no issues from latest `master`. Thanks for the update!

**Pull request merged**
